server:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - .:/var/app
  ports:
   - "80:80"
   - "443:443"
assets:
  build: .
  dockerfile: Dockerfile.assets
  volumes:
    - ./src:/var/build/src
    - ./dist:/var/build/dist
    - ./webpack.config.js:/var/build/webpack.config.js
