FROM node:4.2.1

WORKDIR /var/build

VOLUME /var/build/src
VOLUME /var/build/dist

RUN touch /var/build/webpack.config.js
COPY package.json /var/build/package.json

RUN npm install -g webpack
RUN npm install

CMD ["webpack", "--colors", "--progress", "-d", "--watch"]
